### ISSUE TITLE
for Arch users..

### ISSUE THREAD

**Issue by jazzzy1971** [token2/fido2-manage#1]
Hi,
i just installed it on arch linux (endeavourOS).
Did not use the 2 lines with apt, worked fine

For the gui, i did

`sudo pacman -S tk`

instead of python3-tk

jazzzy

**Comment by token2** [comment]
Hello and thanks for your message.
You submitted this as an issue, but seems like you managed to install this. Shall this be instead an additional set of instructions to be added to README instead?

**Comment by jazzzy1971** [comment]
Hello,
yes, it is meant as help for other users. The README for now is only Ubuntu/Debian, maybe it should be for more Distros.

**Comment by token2** [comment]
Thanks, so are the steps for Arch as below?
`git clone https://github.com/Token2/fido2-manage.git`

`cd fido2-manage`

`sudo apt install -y zlib1g-dev pkg-config`

`sudo apt install -y cmake libcbor-dev libpcsclite-dev libssl-dev libudev-dev`

`rm -rf build && mkdir build && cd build && cmake -USE_PCSC=ON ..`

`cd ..`

`make -C build`

`sudo make -C build install`

`sudo ldconfig`

`chmod 755 fido2-manage.sh`

 ~~`sudo apt install -y python3-tk`~~

 `sudo pacman -S tk`

`python3 gui.py`

**Comment by jazzzy1971** [comment]
Hello,
no, there is no apt on arch.
git clone https://github.com/Token2/fido2-manage.git

cd fido2-manage

rm -rf build && mkdir build && cd build && cmake -USE_PCSC=ON ..

cd ..

make -C build

sudo make -C build install

sudo ldconfig

chmod 755 fido2-manage.sh

sudo apt install -y python3-tk

sudo pacman -S tk

python3 gui.py

worked for me, 

:)

**Comment by token2** [comment]
closing as the solution is based on using different commands for compilation, so basically a documentation issue, not code-related
Thanks for contributing!
