### ISSUE TITLE
Install on Elementary OS7.1

### ISSUE THREAD

**Issue by jhergeth** [token2/fido2-manage#10]
Tried to install on elementary OS 7.1 (Ubuntu 22.04.3 LTS, Linux 6.8.0-40-generic) and got this error:
`:~/fido2-manage$ ./fido2-manage.sh -list
[Error] Error executing /usr/local/bin/fido2-token2 -L: /usr/local/bin/fido2-token2: symbol lookup error: /usr/local/bin/fido2-token2: undefined symbol: fido_cbor_info_rk_remaining
`
Any suggestions?

**Comment by token2** [comment]
we tested on the same build and could not replicate the issue. 
Did you get any error when compiling/installing `fido2-token2` ?

**Comment by jhergeth** [comment]
No, sorry, i did the full installation again, no errors appeared.

**Comment by token2** [comment]
> /usr/local/bin/fido2-token2 -L

Do you still get errors when launching " /usr/local/bin/fido2-token2 -L" ?

**Comment by jhergeth** [comment]
Yes, all the same:
`/usr/local/bin/fido2-token2 -L
/usr/local/bin/fido2-token2: symbol lookup error: /usr/local/bin/fido2-token2: undefined symbol: fido_cbor_info_rk_remaining
`

**Comment by token2** [comment]
> Yes, all the same: `/usr/local/bin/fido2-token2 -L /usr/local/bin/fido2-token2: symbol lookup error: /usr/local/bin/fido2-token2: undefined symbol: fido_cbor_info_rk_remaining `

Thanks for checking. Again, we cannot replicate the issue on the same build.
The only instance when such an error is thrown is when you do not run `sudo ldconfig` after the installation.

**Comment by token2** [comment]
> I started the script with sudo and it works

Probably this has something to do with your particular user's settings. Although we did not succeed to replicate this.

**Comment by token2** [comment]
closing this issue as there was a workaround identified and the issue cannot be replicated (so we cannot fix it)
