### ISSUE TITLE
Install fails on Ubuntu 24.04 

### ISSUE THREAD

**Issue by Kiendeleo** [token2/fido2-manage#14]
It appears that  both the automated script and the instructions fail when installation is attempted on Ubuntu 24.04

`fidotools/fido2-manage/tools/pin.c: In function ‘pin_set2’:
fidotools/fido2-manage/tools/pin.c:115:24: error: cast discards ‘const’ qualifier from pointer target type [-Werror=cast-qual]
  115 |         explicit_bzero((void*)pin1, strlen(pin1));
      |                        ^
`

**Comment by mwick83** [comment]
Same on debian testing with "gcc version 14.2.0 (Debian 14.2.0-6)"

**Comment by token2** [comment]
thanks for reporting, checking now

**Comment by token2** [comment]
This was addressed
 @mwick83 , @Kiendeleo can you please give another try?

**Comment by mwick83** [comment]
Builds fine for me now! Thanks!

**Comment by token2** [comment]
@mwick83 thanks. Closing this for now, feel free to reopen if any issues
