### ISSUE TITLE
macos build

### ISSUE THREAD

**Issue by schack** [token2/fido2-manage#4]
Trying to build on macos, what am I missing ?

CMake Error at tools/CMakeLists.txt:54 (install):
  install TARGETS given target "fido2-token2" which does not exist.

-- MANDOC_PATH: /usr/bin/mandoc
-- GZIP_PATH: /usr/bin/gzip
-- Configuring incomplete, errors occurred!
STL-R7N4H9RQF6:build henj$ cd ..
STL-R7N4H9RQF6:fido2-manage henj$ make -C build
make: *** No targets specified and no makefile found.  Stop.

**Comment by token2** [comment]
Good morning - our fault, there was a typo in the Cmake list .
Fixed, should compile now. Please confirm

**Comment by schack** [comment]
Perfect, that did the trick, thanks a lot
