### ISSUE TITLE
Set PIN not possible

### ISSUE THREAD

**Issue by dr-br** [token2/fido2-manage#5]
I try to set the PIN, it gives me the following:
```
[samuel@desktop fido2-manage]$ ./fido2-manage.sh -changePIN -device 1
[Info] Enter the old and new PIN below.
Enter current PIN for /dev/hidraw6: 
Enter new PIN for /dev/hidraw6: 
Enter the same PIN again: 
fido2-token2: fido_dev_set_pin: FIDO_ERR_PIN_NOT_SET
```
Version:
```
FIDO2 Token Management Tool
v 0.2.2
```

OS: Manjaro

**Comment by dr-br** [comment]
EDIT:

With Chromium browser, Setting the PIN works.

**Comment by token2** [comment]
Hello, -changePIN is to change an existing PIN. For a new PIN, you should use -setPIN (as described in the documentation: `-setPIN -device [number]: Set a PIN of a specific device (for new or freshly reset devices).` )

**Comment by dr-br** [comment]
Perfect, works. Thanks!
