### ISSUE TITLE
Yubico OTP possible?

### ISSUE THREAD

**Issue by dr-br** [token2/fido2-manage#6]
Yubico OTP is well documented [1]. Is it possible to create such a key with a token2 device?

[1]: https://developers.yubico.com/OTP/OTPs_Explained.html

**Comment by token2** [comment]
Token2 devices have OTP functionality, but it is an additional applet and has nothing to do with FIDO protocol and, naturally, with this repository.
This is well documented on the website. If still questions, please reach out to support@token2.com . This issue will be closed as not relevant.
