### ISSUE TITLE
[GUI] error with password with special characters on "show passkeys"

### ISSUE THREAD

**Issue by codeling** [token2/fido2-manage#7]
I am currently setting up my token2 keys; I configured a PIN for it with special characters in it.

To check the passkey management, I downloaded the [GUI for fido2-manage](https://www.token2.com/site/page/fido2-1-security-key-management-tool-gui-for-fido2-manage-exe) on Windows (edit: not 100% this repository is for that program - but it is the closest one I could find). The initial list of configuration options (number of used/available passkeys etc.) works fine. But when I press on "show passkeys" I get an error message:
```
In Zeile:1 Zeichen:70

+ ... anage.exe -residentKeys -device 1 -domain github.com -pin REDACTED...

+                                                                 ~
Die schließende "}" fehlt im Anweisungsblock oder der Typdefinition.
```
(Translation: The closing "}" is missing in the statement block or type definition.)

The REDACTED part is my PIN which contains several special characters. I strongly suspect either the "{" or "\\" special characters in my PIN to be responsible for this message, yet I did not see any restrictions on which special characters can be used? Not during setup but also not in the [PIN complexity description](https://www.token2.com/site/page/token2-fido2-pin-see-the-pin-complexity-in-action).

If these special characters should not be used, I'd expect them to be disallowed when setting up the PIN; if they are allowed, I'd expect the GUI to not fail with an error with such a key.

After the error message, a list opens with one entry; there is one passkey on the device, so the list has the right length; but the entry is just empty:
![fido2-manage-passkey-list](https://github.com/user-attachments/assets/b2e7b5b9-d22a-43d7-b7d8-e33b2f27ef30)

A minor thing - the dialog with the passkey list can be resized, but its layout actually doesn't adapt to the resizing - if I make it smaller, the delete button just gets hidden:
![fido2-manage-passkey-list-smaller](https://github.com/user-attachments/assets/13768fcf-3222-43a4-8a86-82a3f06d6b0a)

~~On a side note, when trying to test this with the command prompt version, I noticed that fido2-manage.exe opens a separate command prompt window, which closes immediately after starting up (so the output cannot be read since it doesn't linger). Is there any way to make it run in the shell it was opened in?~~
Edit: Found it, needs to be started in a command prompt with administrative rights.

**Comment by token2** [comment]
Hello, the issue actually pertains to a different repository (https://github.com/token2/fido2-manage.ps1/) as this one is for Linux/C++/Python), but we'll discuss it here.

The '{' character is allowed as part of the PIN. The problem arose because this character needs to be escaped in PowerShell. This issue has been addressed by enclosing the PIN in quotes, which was an oversight initially. 

https://github.com/token2/fido2-manage.ps1/blob/f64af728c713e27d69ac11a5304e59f88256fe28/gui.ps1#L201 

Feel free to re-download and re-compile. The signed executables will be uploaded later

**Comment by codeling** [comment]
Thanks for the fast response!
